#ifndef _README_ORG
#define _README_ORG
* Chen Bin (redguardtoo)'s vimrc
- Github: git://github.com/redguardtoo/vimrc.git
- WIN32 is fine
- NO Ruby/Python/Perl dependency. The only language except vim script I can accept is C
- This vimrc is light weight because I'm [[https://github.com/redguardtoo/emacs.d][Emacs user now]]
- No "git submodule"
- Vim 7+ requried

* Install

** Linux

#+BEGIN_SRC sh
git clone https://github.com/redguardtoo/vimrc.git ~/.vim;cd ~/.vim;./install-vimrc.sh
#+END_SRC

** Windows (easy way)

- Install CYGWIN
- In CYGWIN bash shell, run exact the same command as in previous *Linux* section.
- Set the value of environment variable *HOME* to the full path of parent directory of .vim

** Windows (hard way)

- Check out from github
#+BEGIN_SRC sh
cd "C:\Program Files\Vim""
rmdir /s vimfiles # This deletes your old configurations. If you want to keep it, use move instead of rmdir
git clone https://github.com/redguardtoo/vimrc.git vimfiles
#+END_SRC

- Install vimrc. Add the following line at the end of C:\Program Files\Vim\vimrc.
#+BEGIN_SRC sh
source $VIM/vimfiles/vimrc
#+END_SRC

* Plugins
** [[https://github.com/tpope/vim-pathogen][Pathogen]]
Pathogen let us install a plugin as a bundle in ~/.vim/bundle seprately.

** [[https://github.com/preservim/nerdtree][Nerd Tree]]
A tree explorer plugin for navigating the filesystem.

Useful commands:
- `:Bookmark [name]` - bookmark any directory as name
- `:NERDTree [name]` - open the bookmark [name] in Nerd Tree

** [[https://github.com/preservim/nerdcommenter][NERD commenter]]
Press ",ci" or ",cc" to comment/uncomment lines.

** [[http://www.vim.org/scripts/script.php?script_id=1849][AutoClose]] 
Inserts matching bracket, paren, brace or quote.

** [[https://github.com/tpope/vim-surround][vim-surround]] 
deal with pairs of surroundings.

** [[https://github.com/andymass/vim-matchup][vim-matchup]] 
match-up is a plugin that lets you highlight, navigate, and operate on sets of matching text. It extends vim's % key to language-specific words instead of just single characters.

** [[http://www.vim.org/scripts/script.php?script_id=1234][YankRing]] 
Maintains a history of previous yanks, changes and deletes.

Run `:help yankring` to see more info.

** [[https://github.com/ctrlpvim/ctrlp.vim][ctrlp.vim]]
Search files

** [[https://github.com/preservim/tagbar][tagbar]]
List symbols in current file

** easymotion
Press ";;" jump to word by its first two characters

** [[https://github.com/tpope/vim-fugitive][vim-fugitive]]
Fugitive is the premier Vim plugin for Git. Or maybe it's the premier Git plugin for Vim? Either way, it's "so awesome, it should be illegal". That's why it's called Fugitive.

** zoomwin
Zoom in/out window. Press ",ff"

** undotree
Undo and redo in tree

* Other good references
- [[http://amix.dk/vim/vimrc.html]]
- [[http://spf13.com/post/perfect-vimrc-vim-config-file]]
#endif // for #ifndef _README_ORG
