* Chen Bin (redguardtoo)'s vimrc
- Light weight
- Works out of box (need Find&Grep to process files; Git&Ctags for coding)
- Vim 9.1 required

* Install
** Linux

#+BEGIN_SRC sh
git clone https://github.com/redguardtoo/vimrc.git ~/.vim;cd ~/.vim;./install-vimrc.sh
#+END_SRC

** Windows (easy way)

- Install CYGWIN
- In CYGWIN bash shell, run exact the same command as in previous *Linux* section.
- Set the value of environment variable *HOME* to the full path of parent directory of .vim

** Windows (hard way)

- Check out from github
#+BEGIN_SRC sh
cd "C:\Program Files\Vim""
rmdir /s vimfiles # This deletes your old configurations. If you want to keep it, use move instead of rmdir
git clone https://github.com/redguardtoo/vimrc.git vimfiles
#+END_SRC

- Install vimrc. Add the following line at the end of C:\Program Files\Vim\vimrc.
#+BEGIN_SRC sh
source $VIM/vimfiles/vimrc
#+END_SRC

* Plugins
** [[https://github.com/tpope/vim-surround][vim-surround]]
deal with pairs of surroundings.

** [[https://github.com/tpope/vim-repeat][vim-repeat]
remaps . in a way that plugins can tap into it.
** [[https://github.com/andymass/vim-matchup][vim-matchup]]
match-up is a plugin that lets you highlight, navigate, and operate on sets of matching text. It extends vim's % key to language-specific words instead of just single characters.

** [[https://github.com/vim-fuzzbox/fuzzbox.vim][fuzzbox.vim]]
Press ",kk" to search files in project root. ",xf" to search files"

** [[https://github.com/preservim/tagbar][tagbar]]
List symbols in current file

** easymotion
Press ";;" jump to word by its first two characters

** [[https://github.com/tpope/vim-fugitive][vim-fugitive]]
Fugitive is the premier Vim plugin for Git. Or maybe it's the premier Git plugin for Vim? Either way, it's "so awesome, it should be illegal". That's why it's called Fugitive.

** zoomwin
Zoom in/out window. Press ",ff"

** [[https://github.com/rickhowe/diffchar.vim][diffchar.vim]]
Highlight the exact differences, based on characters and words

** [[https://github.com/terryma/vim-expand-region][vim-expand-region]]
Keep pressing "v" to expand region

** [[https://github.com/t9md/vim-choosewin][vim-choosewin]]
Press ",xo" to focus on sub-window (Or just press ",[window-number]")
